{
 "title": "Caddy",
 "description": "Some basic caddy http metrics.",
 "tags": [
  "http",
  "caddy",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(caddy_admin_http_requests_total, service)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(caddy_admin_http_requests_total, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Caddy CPU",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"caddy:2019\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Caddy Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_inuse_bytes) / sum(go_memstats_heap_sys_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "caddy_http_request_duration_seconds_count",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HeapObjects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{instance=~\"caddy:2019\", job=\"caddy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Backed Upstream  ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "repeat": "service",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(caddy_reverse_proxy_upstreams_healthy == 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Restarts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(process_start_time_seconds{instance=\"caddy:2019\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"caddy:2019\", job=\"caddy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{instance=~\"caddy:2019\", job=\"caddy\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Caddy Prometheus Target",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(up{instance=~\"caddy:2019\", job=\"caddy\"}, \"status\", \"ok\", \"\", \"\") != 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}